### ISSUE TITLE
Remove "Drug information" facet from UI

### ISSUE THREAD

**Issue by matthias-samwald** [matthias-samwald/find-me-evidence#29]
There are always no results for the "Drug information" facet, because it is not used in the in the index anymore. It should be removed from the UI.

**Comment by gpetz** [comment]
![screenshot-localhost 81 2015-05-27 14-23-26](https://cloud.githubusercontent.com/assets/455986/7835934/dac804dc-047c-11e5-9e7e-45189d98b1a5.png)
